language: java

sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk7

matrix:
  fast_finish: true

before_install:
  - git submodule update --remote
  - pip install --user -r ome-model/requirements.txt
  - pip install --user -r bio-formats-documentation/requirements.txt

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -DskipSphinxTests=true -B
